/*
TOPIC: DELETING&UPDATING DATA
*/

--SELECT *
--FROM SQLTUTORIAL.DBO.EMPLOYEEDEMOGRAPHICS

--UPDATE SQLTUTORIAL.DBO.EMPLOYEEDEMOGRAPHICS
--SET AGE = 31, GENDER ='FEMALE'
--WHERE FIRSTNAME = 'HOLLY' AND LASTNAME = 'FLEX'

--DELETE FROM SQLTUTORIAL.DBO.EMPLOYEEDEMOGRAPHICS
--WHERE EMPLOYEEID = 1005