--CASE STATEMENT TO SPECIFY CONDITION AND WHAT YOU WANT RETURNED WHEN THAT CONDITION IS MET
--SELECT FirstName, LASTNAME, AGE,
--CASE
--    WHEN AGE > 30 THEN 'OLD'
--	WHEN AGE BETWEEN 27 AND 30 THEN 'YOUNG'
--	ELSE 'BABY'
--	END
--FROM SQLTUTORIAL.DBO.EMPLOYEEDEMOGRAPHICS
--ORDER BY AGE

--SELECT FIRSTNAME, LASTNAME,JOBTITLE, SALARY,
--CASE
--    WHEN JOBTITLE = 'SALESMAN' THEN SALARY + (SALARY * .10)
--	WHEN JOBTITLE = 'ACCOUNTANT' THEN SALARY + (SALARY * .05)
--	WHEN JOBTITLE = 'HR' THEN SALARY + (SALARY * .000001)
--	ELSE SALARY +(SALARY * .03)
--	END AS SALARYAFTERRAISE
--FROM SQLTUTORIAL.DBO.EMPLOYEEDEMOGRAPHICS
--INNER JOIN SQLTUTORIAL.DBO.EMPLOYEESALARY
--ON EMPLOYEEDEMOGRAPHICS.EMPLOYEEID = EMPLOYEESALARY.EMPLOYEEID




